Bosh backup
orange-cloudfoundry/postgresbackup-boshrelease pull request #1
Opened 2016-12-13 16:54 UTC by szaouam

internal orange review

2016-12-13 16:55 UTC, gberche-orange commented on README.md
> +This release aims to support bosh v2 manifest. Currently, only Openstack templates are offered by default,
This release aims to support both v1 and v2 manifests

2016-12-13 17:15 UTC, gberche-orange commented on jobs/pgbackup/spec
> +  pgbackup.proxy.http.host:
naming, consider `` pgbackup.s3.http_proxy_host``  ?

2016-12-13 17:17 UTC, gberche-orange commented on jobs/pgbackup/spec
> +    default: "*"
Consider restoring daily default

2016-12-13 17:18 UTC, gberche-orange commented on jobs/pgbackup/spec
>      default: ""
consider removing the default to make the property mandatory

2016-12-13 17:22 UTC, gberche-orange commented on jobs/pgbackup/templates/bin/pgbackup
> +  "postgres90"
consider restoring 9.5 default (this release is not specific to bosh director). Likely the pgdump/pgrestore are compatible with an old pg db
* CF is 9.4
* Bosh is 9.0

2016-12-13 17:23 UTC, gberche-orange commented on jobs/pgbackup/templates/bin/pgbackup
> -echo "export PGVERSION=$PGVERSION"
consider restoring logs, and refine with AWS S3 bucket and endpoinbt (but not the secret key)

2016-12-15 09:04 UTC, gberche-orange requested changes
Thanks @szaouam for the improvements, some related comments that might require some changes

2016-12-15 09:04 UTC, gberche-orange commented on jobs/pgbackup/spec
> +    default: "\"
will this work on S3 or is this default specific to orange S3 blobstore ?

2016-12-15 09:04 UTC, gberche-orange commented on jobs/pgbackup/spec
> +    default: ""
Do we have use cases for separating http and https proxies ? If not consider a single set of properties for configuring both http and https

2016-12-15 09:04 UTC, gberche-orange commented on jobs/pgbackup/spec
> +    description: "Username for the proxy server"
Username used in http proxy basic authentication

2016-12-15 09:04 UTC, gberche-orange commented on jobs/pgbackup/templates/bin/pgbackup
> +# activate debug mode will enable storing password in logs file,
"activate debug mode implies storing passwords in logs file,"

2016-12-15 09:04 UTC, gberche-orange commented on jobs/pgbackup/templates/bin/pgbackup
> +    echo "ERROR : an other dump is running or the last backup failed , see logs for more details"
lock is released when backup fails, should read "an other dump is still running skipping this backup, see logs for more details"

2016-12-15 09:04 UTC, gberche-orange commented on jobs/pgbackup/templates/bin/pgbackup
> +if [ ! -f "/tmp/backup.lock" ]; then
should probably stop waiting on the lock after a max time, such as 1 day, and clear the backup lock ?

2016-12-16 09:00 UTC, szaouam reviewed
Update release (see comments)

2016-12-16 09:00 UTC, szaouam commented on jobs/pgbackup/spec
> -    default: "\"
removed : Minor type

2016-12-16 09:00 UTC, szaouam commented on jobs/pgbackup/spec
> +    description: "Username used in http proxy basic authentication"
add a single set of properties for configuring both http and https

2016-12-16 09:00 UTC, szaouam commented on jobs/pgbackup/templates/bin/pgbackup
>  fi
update proxy configuration to use a single set of parameters

2016-12-16 09:00 UTC, szaouam commented on jobs/pgbackup/templates/bin/pgbackup
> +
We stop waiting on the lock after 1 day

2016-12-16 09:02 UTC, szaouam commented on config/blobs.yml
> +  size: 2555335
update the gof3r package

2016-12-16 09:03 UTC, szaouam commented on packages/gof3r/spec
> +  - gof3r/gof3r-0.5.0.tar.gz
update the gof3r package

2016-12-16 09:05 UTC, szaouam reviewed
downgrade the gof3r package version to 0.4.10  due to compatibility with current release

2016-12-19 08:58 UTC, szaouam commented on pgbackup-dev
>  "
update help message

2016-12-19 08:58 UTC, szaouam commented on pgbackup-dev
> +      ;;
add openstack stemcells

2016-12-19 08:58 UTC, szaouam reviewed
add openstack support for bosh lite

2017-01-12 14:51 UTC, gberche-orange requested changes
Please consider comments inline for the spec file wording

2017-01-12 14:51 UTC, gberche-orange commented on jobs/pgbackup/spec
> -    default: "s3.amazonaws.com"
Please restore default value as to avoid breaking compatibility of existing deployments

2017-01-12 14:51 UTC, gberche-orange commented on jobs/pgbackup/spec
> +    description: "Username used in http proxy basic authentication"
``Username used in http proxy basic authentication. Setting an empty string will skip proxy authentication (this is the default)."

2017-01-12 14:51 UTC, gberche-orange commented on jobs/pgbackup/spec
> +    description: "Password used in http proxy basic authentication"
"Password used in http proxy basic authentication. Setting an empty string will skip proxy authentication (this is the default)."

2017-01-12 14:51 UTC, gberche-orange commented on jobs/pgbackup/spec
> +    description: "Hostname or Ip address of the proxy server, http://your_proxy_server"
"Hostname or Ip address of the proxy server, http://your_proxy_server. Set an empty string to not configure any proxy (this is the default).

2017-01-12 14:58 UTC, gberche-orange approved these changes

2017-01-12 15:05 UTC, merged